# Generated by Django 5.2 on 2025-10-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0003_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counselor',
        ),
    ]
