# Generated by Django 5.2 on 2025-10-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0003_timeslot'),
    ]

    operations = [
        migrations.RunSQL(
            # Only delete the table if it exists
            sql="""
                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables 
                              WHERE table_name='sysadmin_counselor') THEN
                        DROP TABLE sysadmin_counselor CASCADE;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
