# Generated by Django 5.2 on 2025-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_create_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
