# Generated by Django 5.2 on 2025-10-30 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
        ('sysadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(blank=True, db_column='timeslot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='sysadmin.timeslot'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
