"""
Django settings for myproject project.

Generated by 'django-sysadmin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gl_@(ma(v2(p9chw6emig_^pj)0g79y&l_nr&4^5eo#-$^h_@8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'public',
    'sysadmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',     # PostgreSQL backend
        'NAME': 'guidance',                            # database name
        'USER': 'postgres',                            # PostgreSQL username
        'PASSWORD': 'sysadmin',                        # PostgreSQL password
        'HOST': 'localhost',                           # or server IP if remote
        'PORT': '5432',                                # default PostgreSQL port
    }
}



# Authentication backends
AUTHENTICATION_BACKENDS = [
    'public.backends.StudentIDBackend',  # Try student ID first for public login
    'sysadmin.backends.EmailBackend',    # For admin email login
    'django.contrib.auth.backends.ModelBackend',  # Keep the default backend as fallback
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Authentication settings
LOGIN_URL = '/sysadmin/login/'  # Default login URL (for staff)
LOGIN_REDIRECT_URL = '/sysadmin/dashboard/'  # Default redirect after login (for staff)
LOGOUT_REDIRECT_URL = '/sysadmin/login/'  # Default redirect after logout (for staff)

# Public app specific settings (these will be used by the LoginView in public app)
PUBLIC_LOGIN_URL = '/login/'
PUBLIC_LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect to dashboard after public login
PUBLIC_LOGOUT_REDIRECT_URL = '/login/'

# Media files (uploaded assets like logos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'sysadmin' / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
